[book]
authors = ["Ayoub EL Mhamdi"]
title = "TRPM"
language = "fr"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
no-section-label = true
git-repository-url = "https://github.com/ayoubelmhamdi/TRPM"
edit-url-template = "https://github.com/ayoubelmhamdi/TRPM/tree/master/{path}"

[output.html.playground]
copyable = false

[output.html.print]
enable = false

[preprocessor.preproc]
command = "preproc"
renderer = ["html"]
