[book]
authors = ["Ayoub EL Mhamdi"]
title = "TRPM"
language = "fr"

[build]
create-missing = false

[output.html]
site-url = "/TRPM/"
no-section-label = false
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ayoubelmhamdi/TRPM"
edit-url-template = "https://github.com/ayoubelmhamdi/TRPM/tree/master/{path}"
additional-css = ["./theme/tabbed-code-blocks.css", "./theme/highlight.css"]
additional-js = ["./theme/tabbed-code-blocks.js"]

[preprocessor.katex]
after = ["links"]

# [output.linkcheck]
# optional = true
# warning-policy = "warn"
# traverse-parent-directories = true
# follow-web-links = true
